version: '2'
services:
    cameraviewer-app:
        image: cameraviewer
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cameraviewer-mysql:3306/cameraviewer?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cameraviewer-mysql:
        extends:
            file: mysql.yml
            service: cameraviewer-mysql
